In [3]:
import numpy as np

In [4]:
lst = [1,2,3,4,5]
np.array(lst)

array([1, 2, 3, 4, 5])

In [5]:
np.array([lst, lst])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [6]:
np.array([ [1,2,3], [6,7,8], [1,-4, 24] ])

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [ 1, -4, 24]])

In [7]:
 np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
3 * np.eye(4)

array([[3., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 3.]])

In [9]:
np.zeros(shape = (3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
5 * np.ones(shape = (3,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [11]:
np.ones(shape = (3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(-5, 10)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [14]:
np.arange(-5, 10, 3)

array([-5, -2,  1,  4,  7])

In [15]:
np.arange(100, 10, -5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15])

In [16]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [17]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [18]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.random.rand(3,4)

array([[0.99155134, 0.08534   , 0.12700825, 0.50527204],
       [0.95878227, 0.9283858 , 0.31971519, 0.90017521],
       [0.42461568, 0.94378397, 0.82316153, 0.87372528]])

In [20]:
np.random.rand(3,4,5)

array([[[0.76600719, 0.05443114, 0.46514427, 0.79292707, 0.70888843],
        [0.32512766, 0.33499702, 0.90736617, 0.13100628, 0.54191609],
        [0.18260785, 0.54292984, 0.99807949, 0.53992585, 0.23834368],
        [0.70298357, 0.40629658, 0.56395797, 0.19443411, 0.86226812]],

       [[0.09523556, 0.900838  , 0.41827461, 0.36696729, 0.18386179],
        [0.14688135, 0.76815268, 0.3102401 , 0.20874255, 0.29445006],
        [0.2679225 , 0.44274305, 0.51373412, 0.7949283 , 0.50693937],
        [0.19337676, 0.63420206, 0.3702194 , 0.62497341, 0.51390377]],

       [[0.87064014, 0.13228839, 0.62411811, 0.84696427, 0.5141968 ],
        [0.95671452, 0.61778978, 0.81413097, 0.33697303, 0.86177921],
        [0.78473678, 0.82002202, 0.70471973, 0.70222036, 0.67543325],
        [0.93479129, 0.71474796, 0.29713215, 0.69003558, 0.99487945]]])

In [21]:
np.random.randn(4,5)

array([[-0.48345285, -0.41734278, -2.24208285,  1.14907807,  1.27358158],
       [ 1.02304505, -1.36531878,  0.50358218,  1.5231624 ,  0.46770964],
       [-0.800122  ,  0.4321176 ,  0.85878939,  1.78602174, -1.1472691 ],
       [ 0.39613602, -0.44883869,  0.67924837,  0.21285389,  1.4345173 ]])

In [22]:
np.random.randint(10, 60, 10)

array([55, 35, 47, 13, 47, 27, 10, 41, 22, 43])

In [23]:
mat = np.random.randn(4,5)

In [24]:
mat

array([[ 0.13996667,  0.4748065 ,  1.08248863, -0.3551969 , -2.09570478],
       [ 1.40499345,  1.07481139, -0.41907878, -1.25247716,  0.31284139],
       [-0.38110852,  0.05789476,  0.32342255,  0.01041689, -0.00353916],
       [-1.52534767,  0.32475704, -1.20746256, -0.20122593, -0.40934645]])

type(mat)

In [25]:

type(mat)

numpy.ndarray

In [26]:
mat.size

20

In [27]:
mat.shape

(4, 5)

In [28]:
mat.reshape(10,2).shape

(10, 2)

In [29]:
mat.reshape(4,5).shape

(4, 5)

In [30]:
mat.dtype

dtype('float64')

# Numpy Indexing and selection, Functions

In [31]:
arr = np.arange(50, 70)

In [32]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [33]:
type(arr)

numpy.ndarray

In [34]:
arr + 10

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79])

In [35]:
arr > 65

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True])

In [36]:
arr > 67

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True])

In [37]:
arr>70

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [38]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [39]:
sum(arr > 65)

4

In [40]:
arr - 20

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [41]:
arr * 2

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138])

In [42]:
arr / 5

array([10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8, 12. ,
       12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8])

In [43]:
mat = np.random.rand(5, 5)

In [44]:
mat

array([[0.8060088 , 0.60327116, 0.46694633, 0.09402333, 0.67592136],
       [0.3952804 , 0.25569339, 0.66462372, 0.6074761 , 0.57067186],
       [0.98790283, 0.04180039, 0.86830525, 0.07806617, 0.43352656],
       [0.98940441, 0.72609968, 0.28178422, 0.79602522, 0.50653437],
       [0.8059809 , 0.82348599, 0.36774547, 0.45258317, 0.17203883]])

In [45]:
mat[0,0]

0.8060088035223595

In [46]:
mat[3,4]

0.5065343729251193

mat[1,

In [47]:
mat[1,]

array([0.3952804 , 0.25569339, 0.66462372, 0.6074761 , 0.57067186])

In [48]:
mat[: ,4]

array([0.67592136, 0.57067186, 0.43352656, 0.50653437, 0.17203883])

In [49]:
mat[1:4, :]

array([[0.3952804 , 0.25569339, 0.66462372, 0.6074761 , 0.57067186],
       [0.98790283, 0.04180039, 0.86830525, 0.07806617, 0.43352656],
       [0.98940441, 0.72609968, 0.28178422, 0.79602522, 0.50653437]])

mat[:, 0:2]

In [50]:
mat[:, 0:2]

array([[0.8060088 , 0.60327116],
       [0.3952804 , 0.25569339],
       [0.98790283, 0.04180039],
       [0.98940441, 0.72609968],
       [0.8059809 , 0.82348599]])

In [51]:
mat

array([[0.8060088 , 0.60327116, 0.46694633, 0.09402333, 0.67592136],
       [0.3952804 , 0.25569339, 0.66462372, 0.6074761 , 0.57067186],
       [0.98790283, 0.04180039, 0.86830525, 0.07806617, 0.43352656],
       [0.98940441, 0.72609968, 0.28178422, 0.79602522, 0.50653437],
       [0.8059809 , 0.82348599, 0.36774547, 0.45258317, 0.17203883]])

In [53]:
mat[1:3, 0:2]

array([[0.3952804 , 0.25569339],
       [0.98790283, 0.04180039]])

In [54]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [55]:
np.cos(arr)

array([ 0.96496603,  0.7421542 , -0.16299078, -0.91828279, -0.82930983,
        0.02212676,  0.85322011,  0.89986683,  0.11918014, -0.77108022,
       -0.95241298, -0.25810164,  0.67350716,  0.98589658,  0.39185723,
       -0.56245385, -0.99964746, -0.5177698 ,  0.44014302,  0.99339038])

In [56]:
np.tan(arr)

array([-2.71900612e-01,  9.03086149e-01, -6.05327238e+00, -4.31158197e-01,
        6.73800101e-01, -4.51830879e+01, -6.11273688e-01,  4.84699227e-01,
        8.33085685e+00, -8.25774009e-01,  3.20040389e-01,  3.74316794e+00,
       -1.09750978e+00,  1.69749752e-01,  2.34786031e+00, -1.47003826e+00,
        2.65605178e-02,  1.65231726e+00, -2.04008160e+00, -1.15548546e-01])

In [57]:
np.sum(arr)

1190

In [58]:
np.mean(arr)

59.5

# some more numpy functions


In [60]:
a = np.random.random(size = (3,3))
b = np.random.random(size = (3,3))

In [61]:
a

array([[0.31252739, 0.89321664, 0.03407205],
       [0.20559226, 0.01900009, 0.38108475],
       [0.00285543, 0.09262828, 0.62732457]])

In [62]:
b

array([[0.78003168, 0.79107065, 0.41644582],
       [0.56604018, 0.50818613, 0.52720328],
       [0.40227152, 0.7640614 , 0.92671301]])

In [63]:
np.hstack((a,b))

array([[0.31252739, 0.89321664, 0.03407205, 0.78003168, 0.79107065,
        0.41644582],
       [0.20559226, 0.01900009, 0.38108475, 0.56604018, 0.50818613,
        0.52720328],
       [0.00285543, 0.09262828, 0.62732457, 0.40227152, 0.7640614 ,
        0.92671301]])

In [64]:
np.vstack((a,b))

array([[0.31252739, 0.89321664, 0.03407205],
       [0.20559226, 0.01900009, 0.38108475],
       [0.00285543, 0.09262828, 0.62732457],
       [0.78003168, 0.79107065, 0.41644582],
       [0.56604018, 0.50818613, 0.52720328],
       [0.40227152, 0.7640614 , 0.92671301]])

In [65]:
np.hstack((b,a))

array([[0.78003168, 0.79107065, 0.41644582, 0.31252739, 0.89321664,
        0.03407205],
       [0.56604018, 0.50818613, 0.52720328, 0.20559226, 0.01900009,
        0.38108475],
       [0.40227152, 0.7640614 , 0.92671301, 0.00285543, 0.09262828,
        0.62732457]])

In [66]:
np.vstack((b, a))

array([[0.78003168, 0.79107065, 0.41644582],
       [0.56604018, 0.50818613, 0.52720328],
       [0.40227152, 0.7640614 , 0.92671301],
       [0.31252739, 0.89321664, 0.03407205],
       [0.20559226, 0.01900009, 0.38108475],
       [0.00285543, 0.09262828, 0.62732457]])

In [67]:
a = a * 10

In [68]:
a

array([[3.12527385, 8.93216641, 0.34072046],
       [2.05592264, 0.19000089, 3.81084746],
       [0.02855433, 0.92628279, 6.2732457 ]])

In [69]:
np.floor(a)

array([[3., 8., 0.],
       [2., 0., 3.],
       [0., 0., 6.]])

In [70]:
np.ceil(a)

array([[4., 9., 1.],
       [3., 1., 4.],
       [1., 1., 7.]])

In [71]:
new_mat = np.floor(a)

In [72]:
new_mat

array([[3., 8., 0.],
       [2., 0., 3.],
       [0., 0., 6.]])

In [73]:
np.sum(new_mat)

22.0

In [74]:
np.sum(new_mat, axis = 0)

array([5., 8., 9.])

In [75]:
np.sum(new_mat, axis = 1)

array([11.,  5.,  6.])

In [76]:
np.mean(new_mat)

2.4444444444444446

In [77]:
np.mean(new_mat, axis = 0)

array([1.66666667, 2.66666667, 3.        ])

In [78]:
np.mean(new_mat, axis = 1)

array([3.66666667, 1.66666667, 2.        ])

In [79]:
new_mat

array([[3., 8., 0.],
       [2., 0., 3.],
       [0., 0., 6.]])

In [80]:
np.cumsum(new_mat)

array([ 3., 11., 11., 13., 13., 16., 16., 16., 22.])

In [81]:
np.cumprod(new_mat)

array([ 3., 24.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [82]:
np.unique(new_mat)

array([0., 2., 3., 6., 8.])

In [85]:
np.min(new_mat)
np.min(new_mat, axis = 0)
np.min(new_mat, axis = 1)

array([0., 0., 0.])

In [89]:
np.max(new_mat)
np.max(new_mat, axis = 0)
np.max(new_mat, axis = 1)

array([8., 3., 6.])

In [90]:
arr  = np.arange(20,27)

In [91]:
arr

array([20, 21, 22, 23, 24, 25, 26])

In [92]:
for item in arr:
    print(item)

20
21
22
23
24
25
26


In [93]:
for index, item in enumerate(arr):
    print(index, item)

0 20
1 21
2 22
3 23
4 24
5 25
6 26


# Views vs Copy

In [2]:
import numpy as np

In [3]:

a = np.array([2,5,6,78])

In [4]:
b = a

In [5]:
a, b

(array([ 2,  5,  6, 78]), array([ 2,  5,  6, 78]))

In [6]:
a[0] = -5

In [7]:
a, b

(array([-5,  5,  6, 78]), array([-5,  5,  6, 78]))

In [8]:
id(a), id(b)

(2156742387152, 2156742387152)

In [9]:
c = a.view()

In [10]:
a, b, c

(array([-5,  5,  6, 78]), array([-5,  5,  6, 78]), array([-5,  5,  6, 78]))

In [11]:
id(a), id(b), id(c)

(2156742387152, 2156742387152, 2156742463776)

In [12]:
b[1] = 10

In [13]:
a, b, c

(array([-5, 10,  6, 78]), array([-5, 10,  6, 78]), array([-5, 10,  6, 78]))

In [16]:
c[2] = -2

In [17]:
a, b, c

(array([-5, 10, -2, 78]), array([-5, 10, -2, 78]), array([-5, 10, -2, 78]))

In [18]:
x = a.copy()

In [19]:
a, x

(array([-5, 10, -2, 78]), array([-5, 10, -2, 78]))

In [20]:
id(a), id(x)

(2156742387152, 2156742465056)

In [24]:
x[3] = 700

In [25]:
a, x

(array([-5, 10, -2, 78]), array([ -5,  10,  -2, 700]))

In [26]:
a,b,c,x

(array([-5, 10, -2, 78]),
 array([-5, 10, -2, 78]),
 array([-5, 10, -2, 78]),
 array([ -5,  10,  -2, 700]))

# Insert, Append, Delete

In [27]:
a = np.arange(10, 19)

In [28]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [30]:
np.append(a, [20])
np.append(a, [21, 22])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22])

In [31]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [32]:
b = a.reshape(3,3)

In [33]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [45]:
np.append(b, [50, 51,52])
np.append(b, [[50, 51,52]], axis = 0)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [50, 51, 52]])

In [44]:
np.append(b, [[50], [51],[52]], axis = 1)

array([[10, 11, 12, 50],
       [13, 14, 15, 51],
       [16, 17, 18, 52]])

In [46]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [48]:
np.insert(a,1 , -100)

array([  10, -100,   11,   12,   13,   14,   15,   16,   17,   18])

In [49]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [52]:
np.insert(b, 1, -100)
np.insert(b, 1, -100, axis=0)
np.insert(b, 1, -100, axis=1)

array([[  10, -100,   11,   12],
       [  13, -100,   14,   15],
       [  16, -100,   17,   18]])

In [54]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [55]:
np.delete(a, 2)

array([10, 11, 13, 14, 15, 16, 17, 18])

In [56]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [57]:
np.delete(b, 2, axis =1)

array([[10, 11],
       [13, 14],
       [16, 17]])

In [58]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [60]:
np.delete(b, 2, axis =0)
np.delete(b, 1, axis =1)

array([[10, 12],
       [13, 15],
       [16, 18]])

# Split, Concatenate, Tile and Repeat Array

In [1]:
import numpy as np

In [2]:
a = np.arange(24).reshape(4, 6)

In [3]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
np.split(a,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [5]:
np.split(a, 2)[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [6]:
np.split(a, 2)[1]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
np.split(a, 2, axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [9]:
np.split(a, 2, axis=1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [10]:
np.split(a, 3, axis=1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

In [11]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
b = np.arange(100, 124).reshape(4, 6)

In [13]:
b

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [15]:
np.concatenate((a, b))

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [16]:
np.concatenate((a, b), axis =0)

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [18]:
np.concatenate((a, b), axis =1)

array([[  0,   1,   2,   3,   4,   5, 100, 101, 102, 103, 104, 105],
       [  6,   7,   8,   9,  10,  11, 106, 107, 108, 109, 110, 111],
       [ 12,  13,  14,  15,  16,  17, 112, 113, 114, 115, 116, 117],
       [ 18,  19,  20,  21,  22,  23, 118, 119, 120, 121, 122, 123]])

In [19]:
a = np.arange(5)

In [20]:
a

array([0, 1, 2, 3, 4])

In [21]:
np.tile(a, 3)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [22]:
b = np.arange(8).reshape(2, 4)

In [23]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
np.tile(b, 2)

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7]])

In [25]:
np.tile(b, (2,1))

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
np.tile(b, (2,2))

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7]])

In [27]:
np.tile(b, (5,3))

array([[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7]])

In [28]:
a

array([0, 1, 2, 3, 4])

In [30]:
np.repeat(a, 2)
np.repeat(a, 5)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4])

In [31]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [33]:
np.repeat(b, 2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7])

In [34]:
np.repeat(b, 2, axis = 0)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [35]:
np.repeat(b, 2, axis = 1)

array([[0, 0, 1, 1, 2, 2, 3, 3],
       [4, 4, 5, 5, 6, 6, 7, 7]])

In [36]:
np.repeat(b, 5, axis = 1)

array([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7]])

In [37]:
x = np.array([0,1,2,3,4,5])
y = x[0:4]
y[1] =20

In [38]:
x[1]

20