In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
np.array(lst)

array([1, 2, 3, 4, 5])

In [156]:
type(lst)

list

In [157]:
arr = np.array(lst)

In [158]:
arr

array([1, 2, 3, 4, 5])

In [159]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]

In [160]:
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [161]:
mymatrix = np.array(my_list)

In [162]:
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [163]:
mymatrix.shape

(3, 3)

In [3]:
np.array([lst, lst])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [4]:
np.array([ [1,2,3], [6,7,8], [1,-4, 24] ])

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [ 1, -4, 24]])

In [177]:
 np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
3 * np.eye(4)

array([[3., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 3.]])

In [165]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [167]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.zeros(shape = (3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [168]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [170]:
np.ones((4,10)) +5

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [171]:
np.ones(4) *100

array([100., 100., 100., 100.])

In [8]:
5 * np.ones(shape = (3,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [9]:
np.ones(shape = (3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [164]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [173]:
[1,1,1,1] +10

TypeError: can only concatenate list (not "int") to list

In [175]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [176]:
len(np.linspace(0,10,20))

20

In [11]:
np.arange(-5, 10)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [12]:
np.arange(-5, 10, 3)

array([-5, -2,  1,  4,  7])

In [13]:
np.arange(100, 10, -5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15])

In [14]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [15]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [16]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [179]:
np.random.rand(1)

array([0.38217568])

In [180]:
np.random.rand(4)

array([0.8718694 , 0.77379579, 0.88771591, 0.14698905])

In [181]:
np.random.rand(5,5)

array([[0.86863938, 0.52944065, 0.01483036, 0.95345978, 0.30026167],
       [0.49167143, 0.99103828, 0.9574994 , 0.11137242, 0.70738587],
       [0.58630407, 0.13855434, 0.44271785, 0.77774207, 0.98182315],
       [0.55270319, 0.87086566, 0.99663302, 0.10746787, 0.08928499],
       [0.20138403, 0.19979996, 0.50045594, 0.3808574 , 0.69518579]])

In [183]:
np.random.rand(10)

array([0.97545873, 0.87917659, 0.78668477, 0.80624806, 0.76650548,
       0.52993975, 0.01041122, 0.21727935, 0.2231343 , 0.72983561])

In [ ]:
# np.randon.normal

In [185]:
np.random.randint(1,100,10)

array([38, 37, 41,  2, 86,  7, 36, 40, 12, 43])

In [186]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [187]:
arr = np.arange(25)

In [188]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [192]:
arr.shape

(25,)

In [189]:
ranarr = np.random.randint(0,50,10)

In [190]:
ranarr

array([47,  9, 13, 40,  4, 40, 28,  0, 46,  5])

In [193]:
arr.reshape(5,3)

ValueError: cannot reshape array of size 25 into shape (5,3)

In [191]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [194]:
ranarr.max()

47

In [195]:
ranarr

array([47,  9, 13, 40,  4, 40, 28,  0, 46,  5])

In [196]:
ranarr.argmax()

0

In [197]:
ranarr.argmin()

7

In [198]:
ranarr.dtype

dtype('int32')

In [18]:
np.random.rand(3,4,5)

array([[[0.14360829, 0.35745099, 0.10584849, 0.97751064, 0.56037759],
        [0.61204013, 0.47207519, 0.75337159, 0.9634188 , 0.19044194],
        [0.11780585, 0.72573757, 0.85446818, 0.8357777 , 0.75762377],
        [0.8841231 , 0.39956884, 0.80564533, 0.65304441, 0.21443919]],

       [[0.88777174, 0.5140849 , 0.6551672 , 0.27185857, 0.5409408 ],
        [0.65169768, 0.4918881 , 0.95543908, 0.75454992, 0.40536302],
        [0.93176087, 0.85310892, 0.89543668, 0.05449158, 0.67992495],
        [0.50405495, 0.3529264 , 0.98366072, 0.02458589, 0.55926822]],

       [[0.07589935, 0.25072249, 0.04972333, 0.3449426 , 0.76808142],
        [0.25556757, 0.33060964, 0.26837701, 0.25320532, 0.34310544],
        [0.37156981, 0.10021117, 0.88109542, 0.07189733, 0.54984522],
        [0.26760867, 0.17525002, 0.39536815, 0.19412637, 0.1463837 ]]])

In [19]:
np.random.randn(4,5)

array([[-0.53486877, -0.51526299,  0.38646103,  1.21559473, -0.40991781],
       [ 0.41719395, -1.64516504,  2.05966984,  1.13858039, -1.69671048],
       [-1.42565373,  0.03174726, -1.44780847,  0.82165262,  0.02634207],
       [-1.49806323, -0.6171688 ,  0.37271864, -1.20193452,  0.47535943]])

In [20]:
np.random.randint(10, 60, 10)

array([47, 45, 49, 58, 41, 54, 55, 34, 42, 52])

In [21]:
mat = np.random.randn(4,5)

In [22]:
mat

array([[-0.73757727,  0.19471202, -0.14770905, -1.33823841,  0.22179364],
       [-0.74514197, -1.05703994,  0.46201527,  1.87149412,  1.06350825],
       [ 0.28372136,  0.16212357,  1.5819814 , -1.11167505, -0.26424271],
       [-0.05363853, -0.0919432 , -2.47778851,  0.63340102, -1.98259174]])

type(mat)

In [23]:

type(mat)

numpy.ndarray

In [24]:
mat.size

20

In [25]:
mat.shape

(4, 5)

In [26]:
mat.reshape(10,2).shape

(10, 2)

In [27]:
mat.reshape(4,5).shape

(4, 5)

In [28]:
mat.dtype

dtype('float64')

# Numpy Indexing and selection, Functions

In [29]:
arr = np.arange(50, 70)

In [30]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [31]:
type(arr)

numpy.ndarray

In [32]:
arr + 10

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79])

In [33]:
arr > 65

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True])

In [34]:
arr > 67

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True])

In [35]:
arr>70

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [36]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [37]:
sum(arr > 65)

4

In [38]:
arr - 20

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [39]:
arr * 2

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138])

In [250]:
arr1 = np.arange(0,10)

In [252]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [251]:
arr1 +arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [253]:
1 / arr1

C:\Users\Priyanka\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [254]:
arr1/arr1

C:\Users\Priyanka\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [255]:
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [256]:
np.log(arr1)

C:\Users\Priyanka\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [257]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [258]:
np.cos(arr1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [259]:
arr1.sum()

45

In [260]:
arr1.mean()

4.5

In [261]:
arr1.max()

9

In [262]:
arr1_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [263]:
arr1_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [264]:
arr1_2d.shape

(3, 4)

In [265]:
arr1_2d.sum()

78

In [268]:
# Give me the sum acroos the rows
arr1_2d.sum(axis=0)
# Sum of values of the columns

array([15, 18, 21, 24])

In [269]:
arr1_2d.sum(axis=1)

array([10, 26, 42])

In [204]:
new_arr=arr / 5

In [205]:
new_arr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [206]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576],
      dtype=int32)

In [199]:
arr[8]

8

In [200]:
arr[1:5]

array([1, 2, 3, 4])

In [201]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [202]:
arr[:5]

array([0, 1, 2, 3, 4])

In [203]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [207]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [208]:
slice_of_arr = arr[0:6]

In [209]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [210]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [212]:
slice_of_arr[:] = 99

In [213]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [214]:
arr    # Original array is affected to avoid this use copy function

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [215]:
arr_copy = arr.copy()

In [216]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [218]:
arr_copy[:] = 100

In [219]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [220]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

## Indexing on 2D array

In [228]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [229]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [230]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [231]:
arr_2d.shape

(3, 3)

In [234]:
arr_2d[1]

array([20, 25, 30])

In [233]:
arr_2d[1][1]

25

In [235]:
arr_2d[1,1]

25

In [236]:
arr_2d[2,2]

45

In [237]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [238]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [239]:
arr = np.arange(1,11)

In [240]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [241]:
bool_arr = arr > 4

In [242]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [243]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [244]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [245]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [247]:
arr[arr<=6]

array([1, 2, 3, 4, 5, 6])

In [41]:
mat = np.random.rand(5, 5)

In [42]:
mat

array([[0.61023294, 0.80137918, 0.4579768 , 0.8826827 , 0.57254486],
       [0.56113719, 0.16179874, 0.06399912, 0.11000625, 0.17913513],
       [0.84744319, 0.82400652, 0.55769526, 0.40912851, 0.13683744],
       [0.32434451, 0.77139321, 0.73317235, 0.91947605, 0.85886017],
       [0.92928583, 0.78040651, 0.5792687 , 0.05523698, 0.0712554 ]])

In [43]:
mat[0,0]

0.6102329416597273

In [44]:
mat[3,4]

0.8588601743536468

mat[1,

In [45]:
mat[1,]

array([0.56113719, 0.16179874, 0.06399912, 0.11000625, 0.17913513])

In [46]:
mat[: ,4]

array([0.57254486, 0.17913513, 0.13683744, 0.85886017, 0.0712554 ])

In [47]:
mat[1:4, :]

array([[0.56113719, 0.16179874, 0.06399912, 0.11000625, 0.17913513],
       [0.84744319, 0.82400652, 0.55769526, 0.40912851, 0.13683744],
       [0.32434451, 0.77139321, 0.73317235, 0.91947605, 0.85886017]])

mat[:, 0:2]

In [48]:
mat[:, 0:2]

array([[0.61023294, 0.80137918],
       [0.56113719, 0.16179874],
       [0.84744319, 0.82400652],
       [0.32434451, 0.77139321],
       [0.92928583, 0.78040651]])

In [49]:
mat

array([[0.61023294, 0.80137918, 0.4579768 , 0.8826827 , 0.57254486],
       [0.56113719, 0.16179874, 0.06399912, 0.11000625, 0.17913513],
       [0.84744319, 0.82400652, 0.55769526, 0.40912851, 0.13683744],
       [0.32434451, 0.77139321, 0.73317235, 0.91947605, 0.85886017],
       [0.92928583, 0.78040651, 0.5792687 , 0.05523698, 0.0712554 ]])

In [50]:
mat[1:3, 0:2]

array([[0.56113719, 0.16179874],
       [0.84744319, 0.82400652]])

In [51]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [52]:
np.cos(arr)

array([ 0.96496603,  0.7421542 , -0.16299078, -0.91828279, -0.82930983,
        0.02212676,  0.85322011,  0.89986683,  0.11918014, -0.77108022,
       -0.95241298, -0.25810164,  0.67350716,  0.98589658,  0.39185723,
       -0.56245385, -0.99964746, -0.5177698 ,  0.44014302,  0.99339038])

In [53]:
np.tan(arr)

array([-2.71900612e-01,  9.03086149e-01, -6.05327238e+00, -4.31158197e-01,
        6.73800101e-01, -4.51830879e+01, -6.11273688e-01,  4.84699227e-01,
        8.33085685e+00, -8.25774009e-01,  3.20040389e-01,  3.74316794e+00,
       -1.09750978e+00,  1.69749752e-01,  2.34786031e+00, -1.47003826e+00,
        2.65605178e-02,  1.65231726e+00, -2.04008160e+00, -1.15548546e-01])

In [54]:
np.sum(arr)

1190

In [55]:
np.mean(arr)

59.5

# some more numpy functions


In [56]:
a = np.random.random(size = (3,3))
b = np.random.random(size = (3,3))

In [57]:
a

array([[0.43737507, 0.28940012, 0.76400229],
       [0.18705631, 0.86146938, 0.41278157],
       [0.99654748, 0.29660614, 0.41810202]])

In [58]:
b

array([[0.73527631, 0.10735563, 0.99608795],
       [0.67112822, 0.59998766, 0.31745231],
       [0.20708451, 0.51374043, 0.42266792]])

In [59]:
np.hstack((a,b))

array([[0.43737507, 0.28940012, 0.76400229, 0.73527631, 0.10735563,
        0.99608795],
       [0.18705631, 0.86146938, 0.41278157, 0.67112822, 0.59998766,
        0.31745231],
       [0.99654748, 0.29660614, 0.41810202, 0.20708451, 0.51374043,
        0.42266792]])

In [60]:
np.vstack((a,b))

array([[0.43737507, 0.28940012, 0.76400229],
       [0.18705631, 0.86146938, 0.41278157],
       [0.99654748, 0.29660614, 0.41810202],
       [0.73527631, 0.10735563, 0.99608795],
       [0.67112822, 0.59998766, 0.31745231],
       [0.20708451, 0.51374043, 0.42266792]])

In [61]:
np.hstack((b,a))

array([[0.73527631, 0.10735563, 0.99608795, 0.43737507, 0.28940012,
        0.76400229],
       [0.67112822, 0.59998766, 0.31745231, 0.18705631, 0.86146938,
        0.41278157],
       [0.20708451, 0.51374043, 0.42266792, 0.99654748, 0.29660614,
        0.41810202]])

In [62]:
np.vstack((b, a))

array([[0.73527631, 0.10735563, 0.99608795],
       [0.67112822, 0.59998766, 0.31745231],
       [0.20708451, 0.51374043, 0.42266792],
       [0.43737507, 0.28940012, 0.76400229],
       [0.18705631, 0.86146938, 0.41278157],
       [0.99654748, 0.29660614, 0.41810202]])

In [63]:
a = a * 10

In [64]:
a

array([[4.37375065, 2.89400121, 7.64002285],
       [1.87056307, 8.61469377, 4.12781569],
       [9.96547485, 2.9660614 , 4.18102024]])

In [65]:
np.floor(a)

array([[4., 2., 7.],
       [1., 8., 4.],
       [9., 2., 4.]])

In [66]:
np.ceil(a)

array([[ 5.,  3.,  8.],
       [ 2.,  9.,  5.],
       [10.,  3.,  5.]])

In [67]:
new_mat = np.floor(a)

In [68]:
new_mat

array([[4., 2., 7.],
       [1., 8., 4.],
       [9., 2., 4.]])

In [69]:
np.sum(new_mat)

41.0

In [70]:
np.sum(new_mat, axis = 0)

array([14., 12., 15.])

In [71]:
np.sum(new_mat, axis = 1)

array([13., 13., 15.])

In [72]:
np.mean(new_mat)

4.555555555555555

In [73]:
np.mean(new_mat, axis = 0)

array([4.66666667, 4.        , 5.        ])

In [74]:
np.mean(new_mat, axis = 1)

array([4.33333333, 4.33333333, 5.        ])

In [75]:
new_mat

array([[4., 2., 7.],
       [1., 8., 4.],
       [9., 2., 4.]])

In [76]:
np.cumsum(new_mat)

array([ 4.,  6., 13., 14., 22., 26., 35., 37., 41.])

In [77]:
np.cumprod(new_mat)

array([4.00000e+00, 8.00000e+00, 5.60000e+01, 5.60000e+01, 4.48000e+02,
       1.79200e+03, 1.61280e+04, 3.22560e+04, 1.29024e+05])

In [78]:
np.unique(new_mat)

array([1., 2., 4., 7., 8., 9.])

In [79]:
np.min(new_mat)
np.min(new_mat, axis = 0)
np.min(new_mat, axis = 1)

array([2., 1., 2.])

In [80]:
np.max(new_mat)
np.max(new_mat, axis = 0)
np.max(new_mat, axis = 1)

array([7., 8., 9.])

In [81]:
arr  = np.arange(20,27)

In [82]:
arr

array([20, 21, 22, 23, 24, 25, 26])

In [83]:
for item in arr:
    print(item)

20
21
22
23
24
25
26


In [84]:
for index, item in enumerate(arr):
    print(index, item)

0 20
1 21
2 22
3 23
4 24
5 25
6 26


# Views vs Copy

In [85]:
import numpy as np

In [86]:

a = np.array([2,5,6,78])

In [87]:
b = a

In [88]:
a, b

(array([ 2,  5,  6, 78]), array([ 2,  5,  6, 78]))

In [89]:
a[0] = -5

In [90]:
a, b

(array([-5,  5,  6, 78]), array([-5,  5,  6, 78]))

In [91]:
id(a), id(b)

(1534404550944, 1534404550944)

In [92]:
c = a.view()

In [93]:
a, b, c

(array([-5,  5,  6, 78]), array([-5,  5,  6, 78]), array([-5,  5,  6, 78]))

In [94]:
id(a), id(b), id(c)

(1534404550944, 1534404550944, 1534404775984)

In [95]:
b[1] = 10

In [96]:
a, b, c

(array([-5, 10,  6, 78]), array([-5, 10,  6, 78]), array([-5, 10,  6, 78]))

In [97]:
c[2] = -2

In [98]:
a, b, c

(array([-5, 10, -2, 78]), array([-5, 10, -2, 78]), array([-5, 10, -2, 78]))

In [99]:
x = a.copy()

In [100]:
a, x

(array([-5, 10, -2, 78]), array([-5, 10, -2, 78]))

In [101]:
id(a), id(x)

(1534404550944, 1534404749072)

In [102]:
x[3] = 700

In [103]:
a, x

(array([-5, 10, -2, 78]), array([ -5,  10,  -2, 700]))

In [104]:
a,b,c,x

(array([-5, 10, -2, 78]),
 array([-5, 10, -2, 78]),
 array([-5, 10, -2, 78]),
 array([ -5,  10,  -2, 700]))

# Insert, Append, Delete

In [105]:
a = np.arange(10, 19)

In [106]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [107]:
np.append(a, [20])
np.append(a, [21, 22])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22])

In [108]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [109]:
b = a.reshape(3,3)

In [110]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [111]:
np.append(b, [50, 51,52])
np.append(b, [[50, 51,52]], axis = 0)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [50, 51, 52]])

In [112]:
np.append(b, [[50], [51],[52]], axis = 1)

array([[10, 11, 12, 50],
       [13, 14, 15, 51],
       [16, 17, 18, 52]])

In [113]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [114]:
np.insert(a,1 , -100)

array([  10, -100,   11,   12,   13,   14,   15,   16,   17,   18])

In [115]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [116]:
np.insert(b, 1, -100)
np.insert(b, 1, -100, axis=0)
np.insert(b, 1, -100, axis=1)

array([[  10, -100,   11,   12],
       [  13, -100,   14,   15],
       [  16, -100,   17,   18]])

In [117]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [118]:
np.delete(a, 2)

array([10, 11, 13, 14, 15, 16, 17, 18])

In [119]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [120]:
np.delete(b, 2, axis =1)

array([[10, 11],
       [13, 14],
       [16, 17]])

In [121]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [122]:
np.delete(b, 2, axis =0)
np.delete(b, 1, axis =1)

array([[10, 12],
       [13, 15],
       [16, 18]])

# Split, Concatenate, Tile and Repeat Array

In [123]:
import numpy as np

In [124]:
a = np.arange(24).reshape(4, 6)

In [125]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [126]:
np.split(a,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [127]:
np.split(a, 2)[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [128]:
np.split(a, 2)[1]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [129]:
np.split(a, 2, axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [130]:
np.split(a, 2, axis=1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [131]:
np.split(a, 3, axis=1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

In [132]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [133]:
b = np.arange(100, 124).reshape(4, 6)

In [134]:
b

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [135]:
np.concatenate((a, b))

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [136]:
np.concatenate((a, b), axis =0)

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [137]:
np.concatenate((a, b), axis =1)

array([[  0,   1,   2,   3,   4,   5, 100, 101, 102, 103, 104, 105],
       [  6,   7,   8,   9,  10,  11, 106, 107, 108, 109, 110, 111],
       [ 12,  13,  14,  15,  16,  17, 112, 113, 114, 115, 116, 117],
       [ 18,  19,  20,  21,  22,  23, 118, 119, 120, 121, 122, 123]])

In [138]:
a = np.arange(5)

In [139]:
a

array([0, 1, 2, 3, 4])

In [140]:
np.tile(a, 3)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [141]:
b = np.arange(8).reshape(2, 4)

In [142]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [143]:
np.tile(b, 2)

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7]])

In [144]:
np.tile(b, (2,1))

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [145]:
np.tile(b, (2,2))

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7]])

In [146]:
np.tile(b, (5,3))

array([[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7]])

In [147]:
a

array([0, 1, 2, 3, 4])

In [148]:
np.repeat(a, 2)
np.repeat(a, 5)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4])

In [149]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [150]:
np.repeat(b, 2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7])

In [151]:
np.repeat(b, 2, axis = 0)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [152]:
np.repeat(b, 2, axis = 1)

array([[0, 0, 1, 1, 2, 2, 3, 3],
       [4, 4, 5, 5, 6, 6, 7, 7]])

In [153]:
np.repeat(b, 5, axis = 1)

array([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7]])

In [154]:
x = np.array([0,1,2,3,4,5])
y = x[0:4]
y[1] =20

In [155]:
x[1]

20

## Excercise on Numpy

In [ ]:
### 1. Import numpy as np

In [270]:
import numpy as np

In [ ]:
### 2. Create an array of 10 zeros

In [271]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
### 3. Create an array of 10 ones

In [272]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
### 4. Create an array of 10 fives

In [273]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
### 5. Create an array of the integers from 10 to 50

In [274]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
### 6. Create an array of all the even integers from 10 to 50

In [275]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [ ]:
### 7. Create a 3*3 matrix with values ranging from 0 to 8

In [304]:
arr = np.arange(9)

In [305]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
### 8. Create a 3*3 identity matrix

In [282]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
### 9. Use NumPy to generate a random number between 0 and 1
#### NOTE : Your result's value should be different from the one shown below

In [284]:
np.random.rand(1)

array([0.52431585])

In [ ]:
### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
#### NOTE : Your result's value should be different from the one shown below

In [285]:
np.random.randn(25)

array([ 0.66255193, -0.19656148,  0.32822664,  1.18704033, -1.16369686,
       -0.51225162, -1.13782864, -0.00434943,  1.98128298, -1.08838357,
       -1.17149192,  0.39448434, -0.80790986,  1.07256604,  0.17846516,
       -0.54353501, -1.29973493, -0.19804486, -1.46283192,  1.14830046,
       -0.59355693, -0.58825069, -0.73237434, -0.64424228, -0.6051392 ])

In [ ]:
## 11. Create the following Matrix

In [309]:
arr = np.arange(1,101)/100
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
## 12. Create an array of 20 linearly spaced points between 0 and 1

In [291]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [298]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [320]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [321]:
mat[3,4]

20

In [322]:
mat[1:4,1:2]

array([[ 7],
       [12],
       [17]])

In [325]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [326]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [328]:
# Or
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [329]:
mat.sum()

325

In [330]:
mat.std()

7.211102550927978

In [331]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
# Bonus question
## we worked a lot with random data with numpy, but there is a way we can insure that we always get the same numbers?

In [332]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])